import { test, expect } from '@playwright/test'

test('intro, onboarding and the full local demo journey', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.evaluate(() => document.fonts.ready)
  await expect(page.getByRole('heading', { name: 'explore your city', includeHidden: true })).toHaveCount(1)
  await page.screenshot({ path: 'test-results/intro-mobile.png' })
  await page.getByRole('link', { name: /Tap anywhere/ }).click()
  await page.getByRole('link', { name: 'Explore the demo without signing in' }).click()
  await expect(page.getByRole('heading', { name: 'bubl only works on foot.' })).toBeVisible()
  await page.screenshot({ path: 'test-results/welcome-mobile.png' })
  await page.getByRole('button', { name: "Let's go" }).click()
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
  await page.getByRole('button', { name: 'Chats', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Good things start with a wave.' })).toBeVisible()
  await page.getByRole('button', { name: 'Walk', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pop it' })).toBeVisible()
  await expect.poll(() => page.locator('.map-tiles img').evaluateAll(images => images.some(image => (image as HTMLImageElement).naturalWidth > 0)), { timeout: 20000 }).toBe(true)
  await page.screenshot({ path: 'test-results/walk-mobile.png' })
  await page.getByRole('button', { name: 'Pop it' }).click()
  await expect(page.getByRole('heading', { name: 'You found the demo bubble' })).toBeVisible()
  await page.getByRole('button', { name: 'Love this spot', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Loved this spot' })).toBeDisabled()
  await page.getByRole('button', { name: 'Wave', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A little hello to Maya.' })).toBeVisible()
  await page.screenshot({ path: 'test-results/wave-mobile.png' })
  await page.getByRole('button', { name: 'Wave at Maya' }).click()
  await expect(page.getByRole('heading', { name: 'Wave sent.' })).toBeVisible()
  await page.getByRole('button', { name: 'Demo: Maya waves back' }).click()
  await expect(page.getByRole('heading', { name: 'You both waved.' })).toBeVisible()
  await page.getByRole('button', { name: 'Open chat' }).click()
  await page.getByRole('textbox', { name: 'Message Maya' }).fill('What a lovely spot!')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByText('What a lovely spot!', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/chat-mobile.png' })
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Chats', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/chats-mobile.png' })
  await page.getByRole('button', { name: 'Drop', exact: true }).click()
  await page.getByLabel('Give it a name').fill('A quiet corner')
  await page.getByLabel('What should someone know about this exact spot?').fill('The perfect place to sit with a coffee and watch the city go by.')
  await page.screenshot({ path: 'test-results/drop-mobile.png' })
  await page.getByRole('button', { name: 'Release bubble' }).click()
  await expect(page.getByRole('heading', { name: 'Your bubble is floating.' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to walking' }).click()
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await page.getByRole('button', { name: /Dropped ·/ }).click()
  await expect(page.getByRole('heading', { name: 'A quiet corner' })).toBeVisible()
  await page.screenshot({ path: 'test-results/you-mobile.png' })
  await page.getByRole('button', { name: 'Open A quiet corner' }).click()
  await expect(page.getByText('The perfect place to sit with a coffee and watch the city go by.')).toBeVisible()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: /Dropped ·/ }).click()
  await page.getByRole('button', { name: 'Delete A quiet corner' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A quiet corner' })).toHaveCount(0)
  await page.getByRole('button', { name: /Popped ·/ }).click()
  await page.getByRole('button', { name: 'Open You found the demo bubble' }).click()
  await expect(page.getByRole('heading', { name: 'You found the demo bubble' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Loved this spot' })).toBeDisabled()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: 'Remove You found the demo bubble' }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open You found the demo bubble' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Chats', exact: true }).click()
  await page.getByRole('button', { name: /Maya.*What a lovely spot/ }).click()
  await page.getByRole('button', { name: 'Delete chat', exact: true }).click()
  await page.getByRole('button', { name: 'Delete chat', exact: true }).last().click()
  await expect(page.getByRole('heading', { name: 'Good things start with a wave.' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Good things start with a wave.' })).toBeVisible()
  expect(errors).toEqual([])
})

test('map zoom, collapsible sheet, fixed viewport and local profile', async ({ page }) => {
  await page.goto('/demo')
  await expect(page.getByRole('button', { name: 'Pop it' })).toBeVisible()
  const map = page.locator('.street-map')
  await expect(map).toHaveAttribute('data-zoom', '16')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(map).toHaveAttribute('data-zoom', '17')
  await page.getByRole('button', { name: 'Zoom out', exact: true }).click()
  await expect(map).toHaveAttribute('data-zoom', '16')
  const touch = await page.context().newCDPSession(page)
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 110, y: 320, id: 1 }, { x: 210, y: 320, id: 2 }] })
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 60, y: 320, id: 1 }, { x: 260, y: 320, id: 2 }] })
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(map).toHaveAttribute('data-zoom', '17')
  await page.mouse.move(170, 300)
  await page.mouse.wheel(0, 100)
  await expect(map).toHaveAttribute('data-zoom', '16')
  const grip = page.getByRole('button', { name: 'Collapse bubble details' })
  const box = await grip.boundingBox()
  await page.mouse.move(box!.x + box!.width / 2, box!.y + box!.height / 2)
  await page.mouse.down(); await page.mouse.move(box!.x + box!.width / 2, box!.y + 100, { steps: 8 }); await page.mouse.up()
  await expect(page.getByRole('button', { name: 'Expand bubble details' })).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('button', { name: 'Pop it' })).toBeHidden()
  await page.screenshot({ path: 'test-results/map-collapsed.png' })
  await page.getByRole('button', { name: 'Expand bubble details' }).click()
  await expect(page.getByRole('button', { name: 'Pop it' })).toBeVisible()
  expect(await page.evaluate(() => document.scrollingElement!.scrollHeight <= innerHeight)).toBe(true)
  expect(await page.locator('.map-marker-layer').evaluate(element => getComputedStyle(element).clipPath)).toMatch(/^inset/)
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await page.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Name', { exact: true }).fill('Shreya')
  await page.getByLabel('Username', { exact: true }).fill('shreya_nyc')
  await page.getByLabel('Profile photo', { exact: true }).setInputFiles('public/bubl/icons/icon-192.png')
  await expect(page.getByRole('button', { name: 'Remove photo' })).toBeVisible()
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByText('@shreya_nyc', { exact: true })).toBeVisible()
  await expect(page.locator('.profile-summary img')).toBeVisible()
  await page.reload()
  await expect(page.getByText('@shreya_nyc', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/profile-saved.png' })
  await page.setViewportSize({ width: 320, height: 568 })
  for (const view of ['walk', 'chats', 'you', 'drop', 'profile']) {
    await page.goto(`/demo?view=${view}`)
    await expect(page.locator('.mobile-shell')).toBeVisible()
    expect(await page.evaluate(() => document.scrollingElement!.scrollHeight <= innerHeight && document.scrollingElement!.scrollWidth <= innerWidth)).toBe(true)
  }
})

test('small screens, reduced motion and frontend-only navigation', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const backendRequests: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) backendRequests.push(request.url()) })
  await page.goto('/')
  expect(await page.locator('.intro-bubbles').evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await page.getByRole('link', { name: /Tap anywhere/ }).click()
  await page.getByRole('link', { name: 'Explore the demo without signing in' }).click()
  await page.getByRole('button', { name: "Let's go" }).click()
  for (const tab of ['Drop', 'Events', 'Chats', 'You']) {
    await page.goto(`/demo?view=${tab.toLowerCase()}`)
    await expect(page.locator('.bubl-app')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.goto('/home')
  await expect(page.getByRole('navigation', { name: 'Main navigation' })).toBeVisible()
  expect(backendRequests).toEqual([])
})

test('a dropped photo reopens after refresh on an HTTP-compatible demo', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(globalThis.crypto, 'randomUUID', { value: undefined, configurable: true }) })
  await page.goto('/demo?view=drop')
  await page.getByRole('button', { name: 'Photo', exact: true }).click()
  await page.getByRole('textbox', { name: 'Give it a name' }).fill('A photo to remember')
  await page.getByLabel('What should someone know about this exact spot?').fill('A little piece of the city.')
  await page.getByLabel('Add a photo', { exact: true }).setInputFiles('public/bubl/icons/icon-192.png')
  await page.getByRole('button', { name: 'Release bubble' }).click()
  await expect(page.getByRole('heading', { name: 'Your bubble is floating.' })).toBeVisible()
  await page.goto('/demo?view=you')
  await page.getByRole('button', { name: /Dropped · 1/ }).click()
  await page.getByRole('button', { name: 'Open A photo to remember' }).click()
  await expect(page.getByRole('heading', { name: 'A photo to remember' })).toBeVisible()
  await expect.poll(() => page.locator('.note-media').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(192)
})

test('location entry and keyboard viewport recover without scrolling the page', async ({ page }) => {
  await page.goto('/demo?view=drop')
  const field = page.getByLabel('Where is this spot?')
  await field.fill('Broadway')
  await expect(page.getByRole('button', { name: /Use your location/ })).toBeVisible()
  await page.getByRole('button', { name: /Use your location/ }).click()
  await expect(field).toHaveValue('Broadway & 115th St')
  await expect(page.locator('#nearby-places')).toHaveCount(0)
  await field.fill('My corner')
  await page.setViewportSize({ width: 393, height: 460 })
  await expect.poll(() => page.locator('.mobile-shell').evaluate(el => Math.round(el.getBoundingClientRect().height))).toBe(460)
  await page.evaluate(() => {
    Object.defineProperty(visualViewport, 'offsetTop', { configurable: true, value: 70 })
    visualViewport!.dispatchEvent(new Event('scroll'))
  })
  await expect.poll(() => page.locator('.mobile-shell').evaluate(el => el.getBoundingClientRect().top)).toBe(70)
  await field.press('Escape')
  await field.blur()
  await page.evaluate(() => {
    delete (visualViewport as unknown as Record<string, unknown>).offsetTop
    visualViewport!.dispatchEvent(new Event('scroll'))
  })
  await page.setViewportSize({ width: 393, height: 852 })
  await expect.poll(() => page.locator('.mobile-shell').evaluate(el => ({ top: el.getBoundingClientRect().top, height: el.getBoundingClientRect().height })) ).toEqual({ top: 0, height: 852 })
  expect(await page.evaluate(() => document.scrollingElement!.scrollHeight <= innerHeight)).toBe(true)
})


test('drop starts at your location and selects a nearby place', async ({ page }) => {
  await page.goto('/demo')
  const pin = page.getByRole('slider', { name: /Your demo location/ })
  await pin.focus()
  for (let step = 0; step < 2; step++) await pin.press('ArrowUp')
  const position = await pin.getAttribute('aria-valuetext')
  await page.getByRole('button', { name: 'Drop', exact: true }).click()
  await expect(page.getByText(`Your location · ${position}`, { exact: true })).toBeVisible()
  const field = page.getByLabel('Where is this spot?')
  await field.fill('Amsterdam')
  await expect(page.getByRole('button', { name: /Amsterdam Ave & 111th St.*m from your location/ })).toBeVisible()
  await page.getByRole('button', { name: /Amsterdam Ave & 111th St.*m from your location/ }).click()
  await expect(field).toHaveValue('Amsterdam Ave & 111th St')
  await expect(page.getByText('Your bubble stays pinned to the demo dot.')).toHaveCount(0)
  await field.fill('My favorite bench')
  await page.getByRole('button', { name: /Use “My favorite bench”/ }).click()
  await page.getByLabel('Give it a name').fill('A lovely bench')
  await page.getByLabel('What should someone know about this exact spot?').fill('Look at the trees.')
  await page.getByRole('button', { name: 'Release bubble' }).click()
  await expect(page.getByRole('heading', { name: 'Your bubble is floating.' })).toBeVisible()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('bubl.demo.v2')!).bubbles.find((b: { placeName: string }) => b.placeName === 'My favorite bench'))
  expect(saved.lat).toBe(40.8038)
  expect(saved.lng).toBe(-73.9624)
  await page.goto('/')
  expect(await page.locator('body').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(37, 43, 97)')
  expect((await page.locator('.bubl-intro').boundingBox())!.y).toBe(0)
})

test('events feed, reactions, location/time gating and local reports', async ({ page }) => {
  await page.goto('/demo?view=events')
  const live = page.locator('.event-card').filter({ has: page.getByRole('heading', { name: 'A little neighborhood social' }) })
  const future = page.locator('.event-card').filter({ has: page.getByRole('heading', { name: 'An afternoon of live music' }) })
  await expect(live.getByRole('button', { name: 'Pop event' })).toBeEnabled()
  await expect(future.getByRole('button', { name: 'Pop event' })).toBeDisabled()
  await live.getByRole('button', { name: 'Heart A little neighborhood social' }).click()
  await live.getByRole('button', { name: 'I’m going' }).click()
  await expect(live.getByRole('button', { name: 'Going', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: 'test-results/events-feed.png' })
  await future.getByRole('button', { name: 'Find it on the map' }).click()
  await expect(page).toHaveURL(/bubble=event-demo-music/)
  await expect(page.locator('#bubble-details')).toContainText('Riverside Dr & 116th St')
  await page.getByRole('navigation').getByRole('button', { name: 'Events', exact: true }).click()
  await page.reload()
  await expect(live.getByRole('button', { name: 'Heart A little neighborhood social' })).toHaveAttribute('aria-pressed', 'true')
  await live.getByRole('button', { name: 'Pop event' }).click()
  await expect(page.getByRole('heading', { name: 'A little neighborhood social' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Map of Lerner Hall · Broadway' })).toHaveCount(1)
  await page.getByRole('button', { name: 'Report A little neighborhood social' }).click()
  await page.getByLabel('What’s wrong?').selectOption('Event canceled or wrong date')
  await page.getByRole('button', { name: 'Save report' }).click()
  await expect(page.getByRole('heading', { name: 'Report saved on this device' })).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: 'You', exact: true }).click()
  await page.getByRole('button', { name: 'Open A little neighborhood social' }).click()
  await expect(page.getByRole('heading', { name: 'A little neighborhood social' })).toBeVisible()
  await page.goto('/demo')
  const pin = page.getByRole('slider', { name: /Your demo location/ })
  for (let step = 0; step < 2; step++) await pin.press('ArrowUp')
  await page.getByRole('navigation').getByRole('button', { name: 'Events', exact: true }).click()
  await expect(live.getByRole('button', { name: 'Pop event' })).toBeDisabled()
  await expect(live.getByText(/Get closer/)).toBeVisible()
  await page.evaluate(() => {
    const events = JSON.parse(localStorage.getItem('bubl.events.v1')!)
    events[0].event.endsAt = new Date(Date.now() - 1000).toISOString()
    localStorage.setItem('bubl.events.v1', JSON.stringify(events))
  })
  await page.reload()
  await expect(live.getByText('This event has ended')).toBeVisible()
  await expect(live.getByRole('button', { name: 'Pop event' })).toBeDisabled()
})

test('drop an event with a photo, venue and schedule, then reopen and delete', async ({ page }) => {
  await page.goto('/demo?view=drop')
  await page.getByRole('button', { name: 'Events', exact: true }).click()
  await page.getByLabel('Event name', { exact: true }).fill('Our neighborhood picnic')
  await page.getByLabel('Where is this spot?').fill('Riverside')
  await page.getByRole('button', { name: /Riverside Dr & 116th St/ }).click()
  const date = (offset: number) => { const d = new Date(Date.now() + offset * 86400000); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
  await page.getByLabel('Starts', { exact: true }).fill(date(1))
  await page.getByLabel('Ends', { exact: true }).fill(date(0))
  await page.getByLabel('What should someone know about this exact spot?').fill('Bring a picnic blanket and a friend.')
  await expect(page.getByRole('button', { name: 'Release bubble' })).toBeDisabled()
  await page.getByLabel('Ends', { exact: true }).fill(date(2))
  await page.getByRole('button', { name: 'Photo', exact: true }).click()
  await page.getByLabel('Add a photo', { exact: true }).setInputFiles('public/bubl/icons/icon-192.png')
  await page.screenshot({ path: 'test-results/event-drop.png' })
  await page.getByRole('button', { name: 'Release bubble' }).click()
  await expect(page.getByRole('heading', { name: 'Your bubble is floating.' })).toBeVisible()
  await page.goto('/demo?view=you')
  await page.getByRole('button', { name: /Dropped · 1/ }).click()
  await page.getByRole('button', { name: 'Open Our neighborhood picnic' }).click()
  await expect(page.getByRole('heading', { name: 'Our neighborhood picnic' })).toBeVisible()
  await expect.poll(() => page.locator('.note-media').evaluate(el => (el as HTMLImageElement).naturalWidth)).toBe(192)
  await expect(page.getByRole('img', { name: 'Map of Riverside Dr & 116th St' })).toHaveCount(1)
  await page.locator('.location-map').scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'test-results/event-note.png' })
  expect(await page.locator('.privacy-note').evaluate(el => parseFloat(getComputedStyle(el).paddingBottom))).toBeGreaterThanOrEqual(30)
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByRole('button', { name: /Dropped · 1/ }).click()
  await page.getByRole('button', { name: 'Delete Our neighborhood picnic' }).click()
  await page.getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open Our neighborhood picnic' })).toHaveCount(0)
  await page.goto('/demo?view=events')
  await expect(page.getByRole('heading', { name: 'Our neighborhood picnic' })).toHaveCount(0)
})


test('frontend login phone verification and Google preview', async ({ page }) => {
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Continue with Google' })).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: 'test-results/login-choice.png' })
  await page.getByRole('button', { name: 'Use phone number' }).click()
  await page.getByLabel('Phone number', { exact: true }).fill('+1 212 555 1234')
  await page.getByRole('button', { name: 'Send code' }).click()
  await page.getByLabel('Verification code').fill('999999')
  await page.getByRole('button', { name: 'Verify', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('123456')
  await page.getByLabel('Verification code').fill('123456')
  await page.getByRole('button', { name: 'Verify', exact: true }).click()
  await expect(page.getByText('This is how other users see you on the street.')).toBeVisible()
  await page.getByLabel('Username', { exact: true }).fill('city_walker')
  await page.getByLabel('Demo password', { exact: true }).fill('pretend-password')
  await page.screenshot({ path: 'test-results/login-handle.png' })
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page).toHaveURL(/welcome/)
  const stored = await page.evaluate(() => JSON.stringify(localStorage))
  expect(stored).toContain('city_walker')
  expect(stored).not.toContain('pretend-password')
  expect(stored).not.toContain('212 555 1234')
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continue with Google' }).click()
  await expect(page.getByText('Google preview · no account connected')).toBeVisible()
  await page.setViewportSize({ width: 320, height: 568 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('home-screen app fills the display and still follows the keyboard', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'standalone', { value: true, configurable: true })
    Object.defineProperty(window.visualViewport, 'height', { get: () => innerHeight - 100, configurable: true })
  })
  await page.goto('/demo')
  const shell = page.locator('.mobile-shell')
  await expect(shell).toBeVisible()
  await expect.poll(() => page.locator('.bottom-nav').evaluate(el => Math.round(el.getBoundingClientRect().bottom))).toBe(852)
  await page.getByRole('button', { name: 'Drop', exact: true }).click()
  await page.getByLabel('Give it a name').focus()
  await expect.poll(() => shell.evaluate(el => Math.round(el.getBoundingClientRect().height))).toBe(752)
  await page.getByLabel('Give it a name').blur()
  await expect.poll(() => shell.evaluate(el => Math.round(el.getBoundingClientRect().height))).toBe(852)
})


test('bubble title is required, description optional, and focus halo is pink', async ({ page }) => {
  await page.goto('/demo?view=drop')
  const title = page.getByLabel('Give it a name')
  await expect(title).toHaveAttribute('required', '')
  await expect(page.getByRole('button', { name: 'Release bubble' })).toBeDisabled()
  await title.fill('Just a title')
  await expect.poll(() => title.evaluate(el => getComputedStyle(el).outlineColor)).toBe('rgb(255, 96, 183)')
  await expect(page.getByLabel('What should someone know about this exact spot?')).not.toHaveAttribute('required', '')
  await page.getByRole('button', { name: 'Release bubble' }).click()
  await expect(page.getByRole('heading', { name: 'Your bubble is floating.' })).toBeVisible()
  const bubble = await page.evaluate(() => JSON.parse(localStorage.getItem('bubl.demo.v2')!).bubbles.find((item: { title: string }) => item.title === 'Just a title'))
  expect(bubble.text).toBe('')
})

test('standalone keeps navigation within the drawable viewport', async ({ page }) => {
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'standalone', { value: true, configurable: true })
    Object.defineProperty(screen, 'width', { value: 393, configurable: true })
    Object.defineProperty(screen, 'height', { value: 932, configurable: true })
  })
  await page.goto('/demo')
  await expect.poll(() => page.locator('.bottom-nav').evaluate(el => el.getBoundingClientRect().bottom)).toBe(852)
  await page.goto('/demo?view=drop')
  await page.evaluate(() => {
    Object.defineProperty(visualViewport, 'height', { value: 500, configurable: true })
    visualViewport!.dispatchEvent(new Event('resize'))
  })
  await page.getByLabel('Give it a name').focus()
  await expect.poll(() => page.locator('.mobile-shell').evaluate(el => el.getBoundingClientRect().height)).toBe(500)
  await page.getByLabel('Give it a name').blur()
  await expect.poll(() => page.locator('.mobile-shell').evaluate(el => el.getBoundingClientRect().height)).toBe(852)
})


for (const standalone of [false, true]) {
  test(`full-screen frame on all pages, installed=${standalone}`, async ({ page }) => {
    await page.addInitScript(installed => {
      Object.defineProperty(navigator, 'standalone', { value: installed, configurable: true })
      Object.defineProperty(navigator, 'userAgent', { value: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1', configurable: true })
    }, standalone)
    for (const route of ['/login', '/welcome', '/demo', '/demo?view=events', '/demo?view=chats', '/demo?view=you', '/demo?view=drop', '/demo?view=profile']) {
      await page.goto(route)
      await expect(page.locator('.mobile-shell')).toBeVisible()
      if (!standalone) {
        await expect.poll(() => page.locator('.mobile-shell').evaluate(el => el.getBoundingClientRect().top + scrollY)).toBe(0)
        await expect.poll(() => page.evaluate(() => scrollY)).toBe(0)
        if (await page.locator('.bottom-nav').count()) expect(await page.locator('.bottom-nav').evaluate(el => el.getBoundingClientRect().bottom)).toBe(852)
        continue
      }
      await expect.poll(() => page.locator('.mobile-shell').evaluate(el => ({ top: el.getBoundingClientRect().top, bottom: el.getBoundingClientRect().bottom, position: getComputedStyle(el).position }))).toEqual({ top: 0, bottom: 852, position: 'fixed' })
      expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true)
      if (await page.locator('.bottom-nav').count()) expect(await page.locator('.bottom-nav').evaluate(el => el.getBoundingClientRect().bottom)).toBe(852)
    }
  })
}
